# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nuance/rpc/status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nuance.rpc import status_code_pb2 as nuance_dot_rpc_dot_status__code__pb2
from nuance.rpc import error_details_pb2 as nuance_dot_rpc_dot_error__details__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nuance/rpc/status.proto',
  package='nuance.rpc',
  syntax='proto3',
  serialized_options=b'\n\016com.nuance.rpcP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17nuance/rpc/status.proto\x12\nnuance.rpc\x1a\x1cnuance/rpc/status_code.proto\x1a\x1enuance/rpc/error_details.proto\"\x88\x03\n\x06Status\x12+\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x16.nuance.rpc.StatusCode\x12\x17\n\x0fstatus_sub_code\x18\x02 \x01(\x05\x12\x17\n\x0fhttp_trans_code\x18\x03 \x01(\x05\x12-\n\x0crequest_info\x18\x04 \x01(\x0b\x32\x17.nuance.rpc.RequestInfo\x12\x34\n\x0estatus_message\x18\x05 \x01(\x0b\x32\x1c.nuance.rpc.LocalizedMessage\x12\'\n\thelp_info\x18\x06 \x01(\x0b\x32\x14.nuance.rpc.HelpInfo\x12\x34\n\x10\x66ield_violations\x18\x07 \x03(\x0b\x32\x1a.nuance.rpc.FieldViolation\x12)\n\nretry_info\x18\x08 \x01(\x0b\x32\x15.nuance.rpc.RetryInfo\x12\x30\n\x0estatus_details\x18\t \x03(\x0b\x32\x18.nuance.rpc.StatusDetailB\x12\n\x0e\x63om.nuance.rpcP\x01\x62\x06proto3'
  ,
  dependencies=[nuance_dot_rpc_dot_status__code__pb2.DESCRIPTOR,nuance_dot_rpc_dot_error__details__pb2.DESCRIPTOR,])




_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='nuance.rpc.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='nuance.rpc.Status.status_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_sub_code', full_name='nuance.rpc.Status.status_sub_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='http_trans_code', full_name='nuance.rpc.Status.http_trans_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_info', full_name='nuance.rpc.Status.request_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='nuance.rpc.Status.status_message', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='help_info', full_name='nuance.rpc.Status.help_info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field_violations', full_name='nuance.rpc.Status.field_violations', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retry_info', full_name='nuance.rpc.Status.retry_info', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_details', full_name='nuance.rpc.Status.status_details', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=494,
)

_STATUS.fields_by_name['status_code'].enum_type = nuance_dot_rpc_dot_status__code__pb2._STATUSCODE
_STATUS.fields_by_name['request_info'].message_type = nuance_dot_rpc_dot_error__details__pb2._REQUESTINFO
_STATUS.fields_by_name['status_message'].message_type = nuance_dot_rpc_dot_error__details__pb2._LOCALIZEDMESSAGE
_STATUS.fields_by_name['help_info'].message_type = nuance_dot_rpc_dot_error__details__pb2._HELPINFO
_STATUS.fields_by_name['field_violations'].message_type = nuance_dot_rpc_dot_error__details__pb2._FIELDVIOLATION
_STATUS.fields_by_name['retry_info'].message_type = nuance_dot_rpc_dot_error__details__pb2._RETRYINFO
_STATUS.fields_by_name['status_details'].message_type = nuance_dot_rpc_dot_error__details__pb2._STATUSDETAIL
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'nuance.rpc.status_pb2'
  # @@protoc_insertion_point(class_scope:nuance.rpc.Status)
  })
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
