# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nuance/asr/v1/resource.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nuance/asr/v1/resource.proto',
  package='nuance.asr.v1',
  syntax='proto3',
  serialized_options=b'\n\025com.nuance.rpc.asr.v1B\rResourceProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cnuance/asr/v1/resource.proto\x12\rnuance.asr.v1\"\xeb\x02\n\x13RecognitionResource\x12>\n\x12\x65xternal_reference\x18\x01 \x01(\x0b\x32 .nuance.asr.v1.ResourceReferenceH\x00\x12\x18\n\x0einline_wordset\x18\x02 \x01(\tH\x00\x12\x11\n\x07\x62uiltin\x18\x03 \x01(\tH\x00\x12\x18\n\x0einline_grammar\x18\x04 \x01(\tH\x00\x12\x30\n\x0bwakeup_word\x18\x08 \x01(\x0b\x32\x19.nuance.asr.v1.WakeupWordH\x00\x12\x30\n\x0bweight_enum\x18\x05 \x01(\x0e\x32\x19.nuance.asr.v1.EnumWeightH\x01\x12\x16\n\x0cweight_value\x18\x06 \x01(\x02H\x01\x12/\n\x05reuse\x18\x07 \x01(\x0e\x32 .nuance.asr.v1.EnumResourceReuseB\x10\n\x0eresource_unionB\x0e\n\x0cweight_union\"\xf7\x01\n\x11ResourceReference\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.nuance.asr.v1.EnumResourceType\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\x1a\n\x12mask_load_failures\x18\x03 \x01(\x08\x12\x1a\n\x12request_timeout_ms\x18\x07 \x01(\r\x12>\n\x07headers\x18\x08 \x03(\x0b\x32-.nuance.asr.v1.ResourceReference.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1b\n\nWakeupWord\x12\r\n\x05words\x18\x01 \x03(\t*\x91\x01\n\x10\x45numResourceType\x12\x1b\n\x17UNDEFINED_RESOURCE_TYPE\x10\x00\x12\x0b\n\x07WORDSET\x10\x01\x12\x14\n\x10\x43OMPILED_WORDSET\x10\x02\x12\r\n\tDOMAIN_LM\x10\x03\x12\x13\n\x0fSPEAKER_PROFILE\x10\x04\x12\x0b\n\x07GRAMMAR\x10\x05\x12\x0c\n\x08SETTINGS\x10\x06*Y\n\x11\x45numResourceReuse\x12\x13\n\x0fUNDEFINED_REUSE\x10\x00\x12\r\n\tLOW_REUSE\x10\x01\x12\x0e\n\nHIGH_REUSE\x10\x05\"\x04\x08\x02\x10\x02\"\x04\x08\x03\x10\x03\"\x04\x08\x04\x10\x04*X\n\nEnumWeight\x12\x12\n\x0e\x44\x45\x46\x41ULT_WEIGHT\x10\x00\x12\n\n\x06LOWEST\x10\x01\x12\x07\n\x03LOW\x10\x02\x12\n\n\x06MEDIUM\x10\x03\x12\x08\n\x04HIGH\x10\x04\x12\x0b\n\x07HIGHEST\x10\x05\x42(\n\x15\x63om.nuance.rpc.asr.v1B\rResourceProtoP\x01\x62\x06proto3'
)

_ENUMRESOURCETYPE = _descriptor.EnumDescriptor(
  name='EnumResourceType',
  full_name='nuance.asr.v1.EnumResourceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_RESOURCE_TYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WORDSET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMPILED_WORDSET', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOMAIN_LM', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SPEAKER_PROFILE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GRAMMAR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SETTINGS', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=693,
  serialized_end=838,
)
_sym_db.RegisterEnumDescriptor(_ENUMRESOURCETYPE)

EnumResourceType = enum_type_wrapper.EnumTypeWrapper(_ENUMRESOURCETYPE)
_ENUMRESOURCEREUSE = _descriptor.EnumDescriptor(
  name='EnumResourceReuse',
  full_name='nuance.asr.v1.EnumResourceReuse',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_REUSE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOW_REUSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGH_REUSE', index=2, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=840,
  serialized_end=929,
)
_sym_db.RegisterEnumDescriptor(_ENUMRESOURCEREUSE)

EnumResourceReuse = enum_type_wrapper.EnumTypeWrapper(_ENUMRESOURCEREUSE)
_ENUMWEIGHT = _descriptor.EnumDescriptor(
  name='EnumWeight',
  full_name='nuance.asr.v1.EnumWeight',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT_WEIGHT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOWEST', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGHEST', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=931,
  serialized_end=1019,
)
_sym_db.RegisterEnumDescriptor(_ENUMWEIGHT)

EnumWeight = enum_type_wrapper.EnumTypeWrapper(_ENUMWEIGHT)
UNDEFINED_RESOURCE_TYPE = 0
WORDSET = 1
COMPILED_WORDSET = 2
DOMAIN_LM = 3
SPEAKER_PROFILE = 4
GRAMMAR = 5
SETTINGS = 6
UNDEFINED_REUSE = 0
LOW_REUSE = 1
HIGH_REUSE = 5
DEFAULT_WEIGHT = 0
LOWEST = 1
LOW = 2
MEDIUM = 3
HIGH = 4
HIGHEST = 5



_RECOGNITIONRESOURCE = _descriptor.Descriptor(
  name='RecognitionResource',
  full_name='nuance.asr.v1.RecognitionResource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='external_reference', full_name='nuance.asr.v1.RecognitionResource.external_reference', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inline_wordset', full_name='nuance.asr.v1.RecognitionResource.inline_wordset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='builtin', full_name='nuance.asr.v1.RecognitionResource.builtin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inline_grammar', full_name='nuance.asr.v1.RecognitionResource.inline_grammar', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wakeup_word', full_name='nuance.asr.v1.RecognitionResource.wakeup_word', index=4,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight_enum', full_name='nuance.asr.v1.RecognitionResource.weight_enum', index=5,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight_value', full_name='nuance.asr.v1.RecognitionResource.weight_value', index=6,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reuse', full_name='nuance.asr.v1.RecognitionResource.reuse', index=7,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='resource_union', full_name='nuance.asr.v1.RecognitionResource.resource_union',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='weight_union', full_name='nuance.asr.v1.RecognitionResource.weight_union',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=48,
  serialized_end=411,
)


_RESOURCEREFERENCE_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='nuance.asr.v1.ResourceReference.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='nuance.asr.v1.ResourceReference.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='nuance.asr.v1.ResourceReference.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=661,
)

_RESOURCEREFERENCE = _descriptor.Descriptor(
  name='ResourceReference',
  full_name='nuance.asr.v1.ResourceReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='nuance.asr.v1.ResourceReference.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='nuance.asr.v1.ResourceReference.uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask_load_failures', full_name='nuance.asr.v1.ResourceReference.mask_load_failures', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_timeout_ms', full_name='nuance.asr.v1.ResourceReference.request_timeout_ms', index=3,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='nuance.asr.v1.ResourceReference.headers', index=4,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RESOURCEREFERENCE_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=661,
)


_WAKEUPWORD = _descriptor.Descriptor(
  name='WakeupWord',
  full_name='nuance.asr.v1.WakeupWord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='nuance.asr.v1.WakeupWord.words', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=690,
)

_RECOGNITIONRESOURCE.fields_by_name['external_reference'].message_type = _RESOURCEREFERENCE
_RECOGNITIONRESOURCE.fields_by_name['wakeup_word'].message_type = _WAKEUPWORD
_RECOGNITIONRESOURCE.fields_by_name['weight_enum'].enum_type = _ENUMWEIGHT
_RECOGNITIONRESOURCE.fields_by_name['reuse'].enum_type = _ENUMRESOURCEREUSE
_RECOGNITIONRESOURCE.oneofs_by_name['resource_union'].fields.append(
  _RECOGNITIONRESOURCE.fields_by_name['external_reference'])
_RECOGNITIONRESOURCE.fields_by_name['external_reference'].containing_oneof = _RECOGNITIONRESOURCE.oneofs_by_name['resource_union']
_RECOGNITIONRESOURCE.oneofs_by_name['resource_union'].fields.append(
  _RECOGNITIONRESOURCE.fields_by_name['inline_wordset'])
_RECOGNITIONRESOURCE.fields_by_name['inline_wordset'].containing_oneof = _RECOGNITIONRESOURCE.oneofs_by_name['resource_union']
_RECOGNITIONRESOURCE.oneofs_by_name['resource_union'].fields.append(
  _RECOGNITIONRESOURCE.fields_by_name['builtin'])
_RECOGNITIONRESOURCE.fields_by_name['builtin'].containing_oneof = _RECOGNITIONRESOURCE.oneofs_by_name['resource_union']
_RECOGNITIONRESOURCE.oneofs_by_name['resource_union'].fields.append(
  _RECOGNITIONRESOURCE.fields_by_name['inline_grammar'])
_RECOGNITIONRESOURCE.fields_by_name['inline_grammar'].containing_oneof = _RECOGNITIONRESOURCE.oneofs_by_name['resource_union']
_RECOGNITIONRESOURCE.oneofs_by_name['resource_union'].fields.append(
  _RECOGNITIONRESOURCE.fields_by_name['wakeup_word'])
_RECOGNITIONRESOURCE.fields_by_name['wakeup_word'].containing_oneof = _RECOGNITIONRESOURCE.oneofs_by_name['resource_union']
_RECOGNITIONRESOURCE.oneofs_by_name['weight_union'].fields.append(
  _RECOGNITIONRESOURCE.fields_by_name['weight_enum'])
_RECOGNITIONRESOURCE.fields_by_name['weight_enum'].containing_oneof = _RECOGNITIONRESOURCE.oneofs_by_name['weight_union']
_RECOGNITIONRESOURCE.oneofs_by_name['weight_union'].fields.append(
  _RECOGNITIONRESOURCE.fields_by_name['weight_value'])
_RECOGNITIONRESOURCE.fields_by_name['weight_value'].containing_oneof = _RECOGNITIONRESOURCE.oneofs_by_name['weight_union']
_RESOURCEREFERENCE_HEADERSENTRY.containing_type = _RESOURCEREFERENCE
_RESOURCEREFERENCE.fields_by_name['type'].enum_type = _ENUMRESOURCETYPE
_RESOURCEREFERENCE.fields_by_name['headers'].message_type = _RESOURCEREFERENCE_HEADERSENTRY
DESCRIPTOR.message_types_by_name['RecognitionResource'] = _RECOGNITIONRESOURCE
DESCRIPTOR.message_types_by_name['ResourceReference'] = _RESOURCEREFERENCE
DESCRIPTOR.message_types_by_name['WakeupWord'] = _WAKEUPWORD
DESCRIPTOR.enum_types_by_name['EnumResourceType'] = _ENUMRESOURCETYPE
DESCRIPTOR.enum_types_by_name['EnumResourceReuse'] = _ENUMRESOURCEREUSE
DESCRIPTOR.enum_types_by_name['EnumWeight'] = _ENUMWEIGHT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognitionResource = _reflection.GeneratedProtocolMessageType('RecognitionResource', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONRESOURCE,
  '__module__' : 'nuance.asr.v1.resource_pb2'
  # @@protoc_insertion_point(class_scope:nuance.asr.v1.RecognitionResource)
  })
_sym_db.RegisterMessage(RecognitionResource)

ResourceReference = _reflection.GeneratedProtocolMessageType('ResourceReference', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESOURCEREFERENCE_HEADERSENTRY,
    '__module__' : 'nuance.asr.v1.resource_pb2'
    # @@protoc_insertion_point(class_scope:nuance.asr.v1.ResourceReference.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _RESOURCEREFERENCE,
  '__module__' : 'nuance.asr.v1.resource_pb2'
  # @@protoc_insertion_point(class_scope:nuance.asr.v1.ResourceReference)
  })
_sym_db.RegisterMessage(ResourceReference)
_sym_db.RegisterMessage(ResourceReference.HeadersEntry)

WakeupWord = _reflection.GeneratedProtocolMessageType('WakeupWord', (_message.Message,), {
  'DESCRIPTOR' : _WAKEUPWORD,
  '__module__' : 'nuance.asr.v1.resource_pb2'
  # @@protoc_insertion_point(class_scope:nuance.asr.v1.WakeupWord)
  })
_sym_db.RegisterMessage(WakeupWord)


DESCRIPTOR._options = None
_RESOURCEREFERENCE_HEADERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
